from pathlib import Path
from core.config import VERSION, COMPANY, APPLICATION_NAME
from core.logger import AtlasLogger


class DocumentBuilder:
    """Generates standard project documentation files."""

    def __init__(self):
        self.logger = AtlasLogger()

    def create(self, project_path: Path, project_name: str):
        self.create_readme(project_path, project_name)
        self.create_changelog(project_path)
        self.create_todo(project_path)
        self.create_license(project_path)
        self.create_version(project_path)

    def create_readme(self, project_path: Path, project_name: str):
        content = f"""# {project_name}

Created with **{APPLICATION_NAME}** by {COMPANY}

- Version: {VERSION}
- Status: In Development
- Author: Ashe Von

## Description

Add your project description here.
"""
        (project_path / "README.md").write_text(content, encoding="utf-8")
        self.logger.success("README.md")

    def create_changelog(self, project_path: Path):
        content = f"""# Changelog

## [{VERSION}] - Initial Creation

- Project structure generated by Atlas
- Standard documentation files created
"""
        (project_path / "CHANGELOG.md").write_text(content, encoding="utf-8")
        self.logger.success("CHANGELOG.md")

    def create_todo(self, project_path: Path):
        content = """# TODO

- [ ] Define art style and references
- [ ] Blockout environment / characters
- [ ] Import assets into Unreal
- [ ] Set up version control (Git)
- [ ] First playable milestone
"""
        (project_path / "TODO.md").write_text(content, encoding="utf-8")
        self.logger.success("TODO.md")

    def create_license(self, project_path: Path):
        content = f"""{APPLICATION_NAME} Project

Copyright (c) {COMPANY}

All rights reserved.
Internal / Portfolio use.
"""
        (project_path / "LICENSE.txt").write_text(content, encoding="utf-8")
        self.logger.success("LICENSE.txt")

    def create_version(self, project_path: Path):
        (project_path / "VERSION.txt").write_text(VERSION + "\n", encoding="utf-8")
        self.logger.success("VERSION.txt")